// Generated by CoffeeScript 1.7.1
(function() {
  var response;

  response = require('express').response;

  response.SendSuccess = function(answer) {
    this.status(200);
    if (answer != null) {
      return this.send(answer);
    } else {
      return this.end();
    }
  };

  response.SendError = function(error, reason) {
    if (reason == null) {
      reason = null;
    }
    reason = reason == null ? error != null ? error.toString() : void 0 : typeof reason === 'function' ? reason(error) : reason;
    this.status(400);
    return this.send({
      reason: reason
    });
  };

  response.SendIfPossible = function(answer, error, reason) {
    if (error == null) {
      return this.SendSuccess(answer);
    } else {
      return this.SendError(error, reason);
    }
  };

  response.SendOkIfPossible = function(error, reason) {
    return this.SendIfPossible(null, error, reason);
  };

}).call(this);

//# sourceMappingURL=response.map
