// Generated by CoffeeScript 1.7.1
(function() {
  var crypto;

  crypto = require('crypto');

  module.exports = {
    createSalt: function() {
      return crypto.randomBytes(128).toString('base64');
    },
    hashPwd: function(salt, pwd) {
      var hmac;
      hmac = crypto.createHmac('sha1', salt);
      return hmac.update(pwd).digest('hex');
    }
  };

}).call(this);

//# sourceMappingURL=security.map
