// Generated by CoffeeScript 1.7.1
(function() {
  String.prototype.contains = function(value) {
    return this.indexOf(value) >= 0;
  };

  String.prototype.startsWith = function(value) {
    return this.indexOf(value) === 0;
  };

  Array.prototype.remove = function(value) {
    var index;
    index = this.indexOf(value);
    if (index >= 0) {
      return this.splice(index, 1);
    }
  };

  Array.prototype.avg = function() {
    var sum, x, _i, _len;
    if (this.length === 0) {
      return 0;
    } else {
      sum = 0;
      for (_i = 0, _len = this.length; _i < _len; _i++) {
        x = this[_i];
        sum += x;
      }
      return sum / this.length;
    }
  };

}).call(this);

//# sourceMappingURL=utils.map
