// Generated by CoffeeScript 1.7.1
(function() {
  String.prototype.contains = function(value) {
    return this.indexOf(value) >= 0;
  };

  String.prototype.startsWith = function(value) {
    return this.indexOf(value) === 0;
  };

  Array.prototype.remove = function(value) {
    var index;
    index = this.indexOf(value);
    if (index >= 0) {
      return this.splice(index, 1);
    }
  };

}).call(this);

//# sourceMappingURL=utils.map
