// Generated by CoffeeScript 1.7.1
(function() {
  var passport,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  passport = require('passport');

  exports.authenticate = function(req, res, next) {
    var auth;
    if (req.body.username) {
      req.body.username = req.body.username.toLowerCase();
    }
    auth = passport.authenticate('local', function(err, user) {
      if (err != null) {
        return next(err);
      } else if (user == null) {
        return res.send({
          success: false
        });
      } else {
        return req.logIn(user, function(err) {
          if (err != null) {
            return next(err);
          } else {
            return res.send({
              success: true,
              user: user
            });
          }
        });
      }
    });
    return auth(req, res, next);
  };

  exports.requireLogin = function(req, res, next) {
    if (!req.isAuthenticated()) {
      res.status(404);
      return res.end();
    } else {
      return next();
    }
  };

  exports.requireRole = function(role) {
    return function(req, res, next) {
      if (!(req.isAuthenticated() && __indexOf.call(req.user.roles, role) >= 0)) {
        res.status(404);
        return res.end();
      } else {
        return next();
      }
    };
  };

}).call(this);

//# sourceMappingURL=auth.map
