// Generated by CoffeeScript 1.7.1
(function() {
  var passport;

  passport = require('passport');

  exports.authenticate = function(req, res, next) {
    var auth, _ref;
    req.body.username = (_ref = req.body.username) != null ? _ref.toLowerCase() : void 0;
    auth = passport.authenticate('local', function(err, user) {
      if (err != null) {
        return next(err);
      } else if (user == null) {
        return res.send({
          success: false
        });
      } else {
        return req.logIn(user, function(err) {
          if (err != null) {
            return next(err);
          } else {
            return res.send({
              success: true,
              user: user.getData()
            });
          }
        });
      }
    });
    return auth(req, res, next);
  };

  exports.requireLogin = function(req, res, next) {
    if (!req.isAuthenticated()) {
      res.status(404);
      return res.end();
    } else {
      return next();
    }
  };

  exports.requireRole = function(role) {
    return function(req, res, next) {
      if (!(req.isAuthenticated() && req.user.hasRole(role))) {
        res.status(404);
        return res.end();
      } else {
        return next();
      }
    };
  };

  exports.logout = function(req, res) {
    req.logout();
    return res.end();
  };

}).call(this);

//# sourceMappingURL=auth.map
