// Generated by CoffeeScript 1.7.1
(function() {
  var passport;

  passport = require('passport');

  exports.authenticate = function(req, res, next) {
    var auth;
    auth = passport.authenticate('local', function(err, user) {
      if (err) {
        return next(err);
      } else if (!user) {
        return res.send({
          success: false
        });
      } else {
        return req.logIn(user, function(err) {
          if (err) {
            return next(err);
          } else {
            return res.send({
              success: true,
              user: user
            });
          }
        });
      }
    });
    return auth(req, res, next);
  };

}).call(this);

//# sourceMappingURL=auth.map
