// Generated by CoffeeScript 1.7.1
(function() {
  var mongoose;

  mongoose = require('mongoose');

  module.exports = function(config) {
    var User, db, userSchema;
    mongoose.connect(config.db);
    db = mongoose.connection;
    db.on('error', console.error.bind(console, 'connection error...'));
    db.once('open', function() {
      return console.log('Database opened successfully');
    });
    userSchema = mongoose.Schema({
      firstName: String,
      lastName: String,
      username: String
    });
    User = mongoose.model('User', userSchema);
    return User.find({}).exec(function(err, collection) {
      if (collection.length === 0) {
        User.create({
          firstName: 'Joe',
          lastName: 'Kowalski',
          username: 'joe'
        });
        User.create({
          firstName: 'Joe2',
          lastName: 'Kowalski',
          username: 'joe2'
        });
        return User.create({
          firstName: 'Grumpy',
          lastName: 'Student',
          username: 'admin'
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=mongoose.map
