// Generated by CoffeeScript 1.7.1
(function() {
  var mongoose, userModel;

  mongoose = require('mongoose');

  userModel = require('../models/User');

  module.exports = function(config) {
    var db;
    mongoose.connect(config.db);
    db = mongoose.connection;
    db.on('error', console.error.bind(console, 'connection error...'));
    db.once('open', function() {
      return console.log('Database opened successfully');
    });
    return userModel.createDefaultUsers();
  };

}).call(this);

//# sourceMappingURL=mongoose.map
