// Generated by CoffeeScript 1.7.1
(function() {
  var LocalStrategy, User, mongoose, passport;

  mongoose = require('mongoose');

  passport = require('passport');

  LocalStrategy = require('passport-local').Strategy;

  User = mongoose.model('User');

  module.exports = function() {
    passport.use(new LocalStrategy(function(username, password, done) {
      return User.findOne({
        username: username
      }).exec(function(err, user) {
        if (err != null) {
          return done(null, false);
        } else if (user != null ? user.authenticate(password) : void 0) {
          return done(null, user);
        } else {
          return done(null, false);
        }
      });
    }));
    passport.serializeUser(function(user, done) {
      if (user) {
        return done(null, user.id);
      } else {
        return done(null, false);
      }
    });
    return passport.deserializeUser(function(id, done) {
      return User.findOne({
        _id: id
      }).exec(function(err, user) {
        if (err != null) {
          return done(err, null);
        } else if (user) {
          return done(null, user);
        }
      });
    });
  };

}).call(this);

//# sourceMappingURL=passport.map
