// Generated by CoffeeScript 1.7.1
(function() {
  var User, auth, mongoose;

  auth = require('./auth');

  mongoose = require('mongoose');

  User = mongoose.model('User');

  module.exports = function(app) {
    app.get('/api/users', auth.requireRole('admin'), function(req, res) {
      return User.find({}).exec(function(err, collection) {
        return res.send(collection);
      });
    });
    app.get('/partials/*', function(req, res) {
      return res.render('../../public/app/' + req.params);
    });
    app.post('/login', auth.authenticate);
    app.post('/logout', function(req, res) {
      req.logout();
      return res.end();
    });
    app.get('*', function(req, res) {
      return res.render('index', {
        bootstrappedUser: req.user ? req.user.getData() : void 0
      });
    });
    return 0;
  };

}).call(this);

//# sourceMappingURL=routes.map
