// Generated by CoffeeScript 1.7.1
(function() {
  var auth;

  auth = require('./auth');

  module.exports = function(app) {
    app.get('/partials/*', function(req, res) {
      return res.render('../../public/app/' + req.params);
    });
    app.post('/login', auth.authenticate);
    app.post('/logout', function(req, res) {
      req.logout();
      return res.end();
    });
    return app.get('/', function(req, res) {
      return res.render('index', {
        bootstrappedUser: req.user ? req.user.getData() : void 0
      });
    });
  };

}).call(this);

//# sourceMappingURL=routes.map
