// Generated by CoffeeScript 1.7.1
(function() {
  describe('UserModel', function() {
    beforeEach(module('app'));
    return describe('isAdmin', function() {
      it('should return false if the roles array does not include \'admin\'', function(UserModel) {
        var user;
        user = new UserModel();
        user.role = ['not admin'];
        return expect(user.isAdmin()).to.be.falsey;
      });
      return it('should return true if the roles array include \'admin\'', function(UserModel) {
        var user;
        user = new UserModel();
        user.role = ['admin'];
        return expect(user.isAdmin()).to.be["true"];
      });
    });
  });

}).call(this);

//# sourceMappingURL=UserModelSpecs.map
