// Generated by CoffeeScript 1.7.1
(function() {
  var Challenge, Course;

  Course = require('mongoose').model('Course');

  Challenge = require('mongoose').model('Challenge');

  exports.getChallenges = function(req, res) {
    return Challenge.find({}).exec(function(err, collection) {
      return res.send(collection);
    });
  };

  exports.getChallengeById = function(req, res) {
    return Challenge.findOne({
      _id: req.params.id
    }).exec(function(err, challenge) {
      return res.send(challenge);
    });
  };

  exports.createChallenge = function(req, res, next) {
    var challengeData;
    challengeData = req.body;
    return Course.findOne({
      _id: challengeData.courseId
    }).exec(function(err, course) {
      if (err != null) {
        res.status(400);
        return res.send({
          reason: 'Cannot find the course'
        });
      } else {
        return Challenge.create(challengeData, function(err, challenge) {
          if (err != null) {
            res.status(400);
            return res.send({
              reason: err.toString()
            });
          } else {
            course.challenges.push(challenge);
            return course.save(function(err) {
              if (err != null) {
                res.status(400);
                return res.send({
                  reason: err.toString()
                });
              } else {
                res.status(200);
                return res.send(challenge);
              }
            });
          }
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=challengesController.map
