// Generated by CoffeeScript 1.7.1
(function() {
  var Challenge, Course, mongoose;

  mongoose = require('mongoose');

  Course = mongoose.model('Course');

  Challenge = mongoose.model('Challenge');

  exports.getCourses = function(req, res) {
    return Course.find({}).exec(function(err, collection) {
      return res.SendIfPossible(collection, err);
    });
  };

  exports.createCourse = function(req, res, next) {
    var courseData;
    courseData = req.body;
    courseData.published = new Date();
    return Course.create(courseData, function(err, course) {
      return res.SendIfPossible(course, err);
    });
  };

  exports.removeCourse = function(req, res, next) {
    var id;
    id = req.params.id;
    return Course.remove({
      _id: id
    }).exec(function(err) {
      if (err != null) {
        return res.SendError(err);
      }
      return Challenge.remove({
        courseId: id
      }).exec(function(err) {
        return res.SendOkIfPossible(err);
      });
    });
  };

}).call(this);

//# sourceMappingURL=coursesController.map
