// Generated by CoffeeScript 1.7.1
(function() {
  var Message;

  Message = require('mongoose').model('Message');

  exports.getMessages = function(req, res) {
    var args, userId;
    userId = req.params.userId;
    args = userId != null ? {
      userId: userId
    } : {};
    return Message.find(args).exec(function(err, collection) {
      return res.SendIfPossible(collection, err);
    });
  };

  exports.createMessage = function(req, res, next) {
    var messageData;
    messageData = req.body;
    return Message.create(messageData, function(err, message) {
      return res.SendIfPossible(message, err);
    });
  };

  exports.saveFeedback = function(req, res, next) {
    var messageData;
    messageData = req.body;
    messageData.userId = req.user._id;
    return Message.create(messageData, function(err, message) {
      return res.SendIfPossible(message, err);
    });
  };

  exports.removeMessage = function(req, res, next) {
    var id;
    id = req.params.id;
    return Message.remove({
      _id: id
    }).exec(function(err) {
      return res.SendOkIfPossible(err);
    });
  };

}).call(this);

//# sourceMappingURL=messagesController.map
