// Generated by CoffeeScript 1.7.1
(function() {
  var Message;

  Message = require('mongoose').model('Message');

  exports.getMessages = function(req, res) {
    var args, userId;
    userId = req.params.userId;
    args = userId != null ? {
      userId: userId
    } : {};
    return Message.find(args).exec(function(err, collection) {
      return res.send(collection);
    });
  };

  exports.createMessage = function(req, res, next) {
    var messageData;
    messageData = req.body;
    return Message.create(messageData, function(err, message) {
      if (err != null) {
        res.status(400);
        return res.send({
          reason: err.toString()
        });
      } else {
        res.status(200);
        return res.send(message);
      }
    });
  };

  exports.removeMessage = function(req, res, next) {
    var id;
    id = req.params.id;
    return Message.remove({
      _id: id
    }).exec(function(err) {
      if (err == null) {
        res.status(200);
        return res.end();
      } else {
        res.status(400);
        return res.send({
          reason: err.toString()
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=messagesController.map
