// Generated by CoffeeScript 1.7.1
(function() {
  var Message, User, mongoose;

  mongoose = require('mongoose');

  Message = mongoose.model('Message');

  User = mongoose.model('User');

  exports.getMessages = function(req, res) {
    var args, userId;
    userId = req.params.userId;
    args = userId != null ? {
      userId: userId
    } : {};
    return Message.find(args).exec(function(err, collection) {
      User.findOne({
        _id: userId
      }).exec(function(err, user) {
        user.unreadMessages = 0;
        return user.save();
      });
      return res.SendIfPossible(collection, err);
    });
  };

  exports.saveFeedback = function(req, res, next) {
    var messageData;
    messageData = req.body;
    messageData.userId = req.user._id;
    return Message.create(messageData, function(err, message) {
      if (err != null) {
        return res.SendError(err);
      }
      req.user.allMessages++;
      req.user.unreadMessages++;
      req.user.save();
      return res.SendSuccess();
    });
  };

  exports.removeMessage = function(req, res, next) {
    var id;
    id = req.params.id;
    return Message.findOne({
      _id: id
    }).exec(function(err, message) {
      return User.findOne({
        _id: message.userId
      }).exec(function(err, user) {
        if (err != null) {
          return res.SendError("Cannot find owner of this message");
        }
        user.allMessages--;
        user.save();
        return Message.remove({
          _id: id
        }).exec(function(err) {
          return res.SendOkIfPossible(err);
        });
      });
    });
  };

}).call(this);

//# sourceMappingURL=messagesController.map
