// Generated by CoffeeScript 1.7.1
(function() {
  var Challenge, Course, Rating, mongoose;

  mongoose = require('mongoose');

  Rating = mongoose.model('Rating');

  Course = mongoose.model('Course');

  Challenge = mongoose.model('Challenge');

  exports.getRatings = function(req, res) {
    var args, userId;
    args = {};
    if (!req.user.hasRole('admin')) {
      userId = req.body.userId;
      args = {
        userId: userId
      };
    }
    return Rating.find(args).exec(function(err, collection) {
      return res.send(collection);
    });
  };

  exports.addRating = function(req, res, next) {
    var model, ratingData;
    ratingData = req.body;
    ratingData.userId = req.body.userId;
    model = ratingData.type === 'course' ? Course : Challenge;
    return model.findOne({
      _id: ratingData.objectId
    }).exec(function(err, element) {
      if (err != null) {
        res.status(400);
        return res.send({
          reason: err.toString()
        });
      } else {
        ratingData.objectId = element._id;
        return Rating.create(ratingData, function(err, rating) {
          if (err != null) {
            res.status(400);
            return res.send({
              reason: err.toString()
            });
          } else {
            res.status(200);
            return res.send(rating);
          }
        });
      }
    });
  };

  exports.updateRating = function(req, res, next) {
    var id;
    id = req.params.id;
    return Rating.findOne({
      _id: id
    }).exec(function(err, rating) {
      if (err != null) {
        res.status(400);
        return res.send({
          reason: err.toString()
        });
      } else {
        rating.rating = req.body.rating;
        return rating.save(function(err) {
          if (err != null) {
            res.status(400);
            return res.send({
              reason: err.toString()
            });
          } else {
            return res.send(rating);
          }
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=ratingsController.map
