// Generated by CoffeeScript 1.7.1
(function() {
  var User, security;

  security = require('../utilities/security');

  User = require('mongoose').model('User');

  exports.getUsers = function(req, res) {
    return User.find({}).exec(function(err, collection) {
      return res.send(collection);
    });
  };

  exports.createUser = function(req, res, next) {
    var userData;
    userData = req.body;
    userData.username = userData.username;
    userData.salt = security.createSalt();
    userData.hashed_pwd = security.hashPwd(userData.salt, userData.password);
    return User.create(userData, function(err, user) {
      if (err != null) {
        if (err.toString().contains('E11000')) {
          err = new Error('Duplicate Username');
        }
        res.status(400);
        return res.send({
          reason: err.toString()
        });
      } else {
        return req.logIn(user, function(err) {
          return res.send(user.getData());
        });
      }
    });
  };

  exports.updateUser = function(req, res, next) {
    var newPassword, userUpdates;
    userUpdates = req.body;
    req.user.username = userUpdates.username;
    req.user.firstName = userUpdates.firstName;
    req.user.lastName = userUpdates.lastName;
    newPassword = userUpdates.password;
    if ((newPassword != null ? newPassword.length : void 0) > 0) {
      req.user.salt = security.createSalt();
      req.user.hashed_pwd = security.hashPwd(req.user.salt, newPassword);
    }
    return req.user.save(function(err) {
      if (err != null) {
        res.status(400);
        return res.send({
          reason: err.toString()
        });
      } else {
        return res.send(req.user.getData());
      }
    });
  };

  exports.removeUser = function(req, res, next) {
    var id;
    id = req.params.id;
    if (req.user._id.toString() === id) {
      res.status(400);
      return res.send({
        reason: 'You cannot remove yourself'
      });
    } else {
      return User.remove({
        _id: id
      }).exec(function(err) {
        if (err == null) {
          res.status(200);
          return res.end();
        } else {
          res.status(400);
          return res.send({
            reason: err.toString()
          });
        }
      });
    }
  };

}).call(this);

//# sourceMappingURL=usersController.map
