// Generated by CoffeeScript 1.7.1
(function() {
  var User, security;

  security = require('../utilities/security');

  User = require('mongoose').model('User');

  exports.getUsers = function(req, res) {
    return User.find({}).exec(function(err, collection) {
      return res.send(collection);
    });
  };

  exports.createUser = function(req, res, next) {
    var userData;
    userData = req.body;
    userData.username = userData.username.toLowerCase();
    userData.salt = security.createSalt();
    userData.hashed_pwd = security.hashPwd(userData.salt, userData.password);
    return User.create(userData, function(err, user) {
      if (err) {
        if (err.toString().indexOf('E11000') > -1) {
          err = new Error('Duplicate Username');
        }
        res.status(400);
        return res.send({
          reason: err.toString()
        });
      } else {
        return req.logIn(user, function(err) {
          return res.send(user);
        });
      }
    });
  };

}).call(this);

//# sourceMappingURL=usersController.map
